export const routes = {
  OnBoarding: "OnBoarding",
  SplashScreen: "SplashScreen",
  SignUpEmail: "SignUpEmail",
  SignUpCode: "SignUpCode",
  SignUpPersonal: "SignUpPersonal",
  SignUpPassword: "SignUpPassword",
  SignInSuccess: "SignInSuccess",
  SignUpSuccess: "SignUpSuccess",
  SignIn: "SignIn",
  SignInCode: "SignInCode",
  ForgotPasswordEmail: "ForgotPasswordEmail",
  ForgotPasswordCode: "ForgotPasswordCode",
  ForgotPasswordSuccess: "ForgotPasswordSuccess",
  ForgotPasswordHome: "ForgotPasswordHome",
  Home: "Home",
  SearchResult: "SearchResult",
  HomeFilter: "HomeFilter",
  PropertyDetailed: "PropertyDetailed",
};
