import Head from "next/head";
import Image from "next/image";
import { Button } from "../components";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header
        className="hero-image"
        style={{
          paddingTop: 70,
          backgroundImage:
            "radial-gradient(79.24% 270.81% at 35.45% 34.74%, rgba(5, 7, 5, 0.8) 0%, rgba(5, 7, 5, 0.712) 100%)",
        }}
      >
        <div style={{ textAlign: "center", marginBottom: 103 }}>
          <img src="/images/logo.svg" />
        </div>
        <h1
          style={{
            fontSize: 32,
            fontWeight: "900",
            fontFamily: "Circular Std",
            textAlign: "center",
            color: "rgba(255, 255, 255, 1)",
          }}
        >
          Miss Olamma Africa
        </h1>
        <h2
          style={{
            fontSize: 14,
            fontFamily: "Circular Std",
            textAlign: "center",
            marginTop: 16,
            color: "rgba(255, 255, 255, 0.9)",
            paddingBottom: 62.5,
          }}
        >
          The Biggest Pan-Igbo Beauty Pageant in the World
        </h2>
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            columnGap: 16,
            paddingBottom: 40,
          }}
        >
          <Button bg="rgba(188, 137, 36, 0.2)" />
          <Button bg="rgba(188, 137, 36, 1)" />
        </div>
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            columnGap: 20,
            paddingBottom: 85,
          }}
        >
          <div
            style={{
              width: 60,
              height: 60,
              borderRadius: 50,
              backgroundColor: "rgba(188, 137, 36, 0.2)",
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <img src="./images/back-arrow.svg" />
          </div>
          <div
            style={{
              width: 60,
              height: 60,
              borderRadius: 50,
              backgroundColor: "rgba(188, 137, 36, 0.2)",
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <img src="./images/forward-arrow.svg" />
          </div>
        </div>
      </header>

      <main>
        <section
          style={{
            padding: "53px 30px",
            backgroundColor: "rgba(5, 7, 5, 0.8)",
          }}
        >
          <div style={{ marginBottom: 105 }}>
            <h2
              style={{
                textAlign: "center",
                color: "rgba(255, 255, 255, 1)",
                fontSize: 22,
                fontWeight: "700",
                fontFamily: "Circular Std",
              }}
            >
              About us
            </h2>
            <p
              style={{
                lineHeight: 1.4,
                color: "rgba(238, 238, 238, 1)",
                fontFamily: 14,
              }}
            >
              Miss Olamma Africa is not only a celebration of the beauty of
              Africa from the eyes of the Igbo women of South East Nigeria, it
              is the acknowledgement of the most virtuous, most valuable, the
              most precious gift of all that the universe has bestowed upon
              humanity, THE WOMAN.
            </p>
          </div>
          <div style={{ marginBottom: 30 }}>
            <h2
              style={{
                color: "rgba(255, 255, 255, 0.9)",
                fontSize: 20,
                fontWeight: "500",
                fontFamily: "Circular Std",
                marginBottom: 17.3,
              }}
            >
              Our vision
            </h2>
            <p
              style={{
                lineHeight: 1.4,
                color: "rgba(226, 226, 226, 0.9)",
                fontFamily: 16,
              }}
            >
              We are determined to create a pan African platform that celebrates
              the African beauty through the eyes of the Igbo Woman.
            </p>
          </div>
          <div style={{ marginTop: 30 }}>
            <h2
              style={{
                color: "rgba(255, 255, 255, 0.9)",
                fontSize: 20,
                fontWeight: "500",
                fontFamily: "Circular Std",
                marginBottom: 17.3,
              }}
            >
              Our mission
            </h2>
            <p
              style={{
                lineHeight: 1.4,
                color: "rgba(226, 226, 226, 0.9)",
                fontFamily: 16,
              }}
            >
              To design an annual contest that allows Igbo African Women to
              express themselves through pageantry.
            </p>
          </div>
          <div style={{ marginTop: 30 }}>
            <h2
              style={{
                color: "rgba(255, 255, 255, 0.9)",
                fontSize: 20,
                fontWeight: "500",
                fontFamily: "Circular Std",
                marginBottom: 17.3,
              }}
            >
              The Contest
            </h2>
            <p
              style={{
                lineHeight: 1.4,
                color: "rgba(226, 226, 226, 0.9)",
                fontFamily: 16,
              }}
            >
              Miss Olamma Africa Pageant is an online voting contest that
              culminates into a grand finale amidst a high-quality audience, the
              media and stakeholders across Nigeria
            </p>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
